### ISSUE TITLE
Arrow currently has no Jackson support module

### ISSUE THREAD

**Issue by androidfred** [arrow-kt/arrow-incubator#14]
STEPS TO REPRODUCE
Create a Jersey resource with an endpoint with params wrapped in a datatype, eg

```kotlin
    @GET
    @Path("/search/user")
    @Timed
    @ResponseMetered
    fun searchUsername(
            @QueryParam("firstName") firstName: String,
            @QueryParam("lastName") lastName: Option<String>)
            : Response {
        //...
    }
```

EXPECTED RESULT
curl url/search/user?firstName=Foo&lastName=Bar results in an Option containing Bar
curl url/search/user?firstName=Foo results in an Option that is empty

ACTUAL RESULT
RunTimeException because there is no equivalent to com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.java for Arrow's Option

MISC
As this is a Jersey/Jackson specific thing, it's NOT a core Arrow feature request per se, but given the popularity of Jackson for JSON serialization and deserialization, it's a pretty important nice to have that could go into a dedicated Jackson support module.

**Comment by MarioAriasC** [comment]
An initial support for Jackson already exists in Arrow Integrations

https://github.com/arrow-kt/arrow-integrations

**Comment by aballano** [comment]
closing this then, thank you all!
