### ISSUE TITLE
Link to `from` in `AQL` docs point to `select`

### ISSUE THREAD

**Issue by broken-codes** [arrow-kt/arrow-incubator#141]
In the docs of `AQL`, the href for `from` is not correct. Currently, it is pointing to https://arrow-kt.io/docs/aql/select/
**Expected**
Link pointed by `href` of `from` should point to: https://arrow-kt.io/docs/aql/from/

![Image showing the issue](https://user-images.githubusercontent.com/62198843/103142586-752d4900-472b-11eb-84d1-d2097c9e3b71.png)

**Comment by rachelcarmena** [comment]
Thank you so much @broken-codes :raised_hands: Would you like to contribute? This file should be fixed: https://github.com/arrow-kt/arrow-incubator/tree/master/arrow-docs/docs/aql/select
