### ISSUE TITLE
["Request"] Make EitherT MonadError parameterized to only `L` and not `L` and `E`

### ISSUE THREAD

**Issue by 1Jajen1** [arrow-kt/arrow-incubator#47]
`EitherTMonadError` is currently defined as a lift-through error instance. This means it will reuse the `MonadError` instance for `F`. This is quite bad because `EitherT<L, F, A>` quite literally "adds" error capabilities to `F` with the error `L`. Not using that is simply wrong.

So the proposed change is:
`EitherTMonadError<L, F, E> -> EitherTMonadError<L, F>` and `raiseError(e) = EitherT.left(e)`.

**Comment by pakoito** [comment]
If it typechecks, great :D

**Comment by 1Jajen1** [comment]
> If it typechecks, great :D

Pretty sure it will. Only interesting part is what to do with the `MonadThrow` and the `Bracket` instances. Not sure whether to lift through or to use `L`...
